// Code generated by "stringer -type=Status -trimprefix=Status"; DO NOT EDIT.

package play

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[StatusUnknown-0]
	_ = x[StatusJoined-1]
	_ = x[StatusExcluded-2]
	_ = x[StatusCollected-3]
	_ = x[StatusShared-4]
	_ = x[StatusSubmitted-5]
	_ = x[StatusFailed-6]
	_ = x[StatusSentinel-7]
}

const _Status_name = "UnknownJoinedExcludedCollectedSharedSubmittedFailedSentinel"

var _Status_index = [...]uint8{0, 7, 13, 21, 30, 36, 45, 51, 59}

func (i Status) String() string {
	if i < 0 || i >= Status(len(_Status_index)-1) {
		return "Status(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Status_name[_Status_index[i]:_Status_index[i+1]]
}
