// Code generated by glean from glean.go:9. DO NOT EDIT.
package rounds

import (
	"context"
	"database/sql"

	"github.com/corverroos/play/internal"
)

const cols = " `id`, `external_id`, `status`, `created_at`, `updated_at`, `version`, `state` "
const selectPrefix = "select " + cols + " from play_rounds where "

func Lookup(ctx context.Context, dbc dbc, id int64) (*internal.Round, error) {
	return lookupWhere(ctx, dbc, "id=?", id)
}

// lookupWhere queries the play_rounds table with the provided where clause, then scans
// and returns a single row.
func lookupWhere(ctx context.Context, dbc dbc, where string, args ...interface{}) (*internal.Round, error) {
	return scan(dbc.QueryRowContext(ctx, selectPrefix+where, args...))
}

// listWhere queries the play_rounds table with the provided where clause, then scans
// and returns all the rows.
func listWhere(ctx context.Context, dbc dbc, where string, args ...interface{}) ([]internal.Round, error) {

	rows, err := dbc.QueryContext(ctx, selectPrefix+where, args...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()

	var res []internal.Round
	for rows.Next() {
		r, err := scan(rows)
		if err != nil {
			return nil, err
		}
		res = append(res, *r)
	}

	return res, rows.Err()
}

func scan(row row) (*internal.Round, error) {
	var g glean

	err := row.Scan(&g.ID, &g.ExternalID, &g.Status, &g.CreatedAt, &g.UpdatedAt, &g.Version, &g.State)
	if err != nil {
		return nil, err
	}

	return &internal.Round{
		ID:         g.ID,
		ExternalID: g.ExternalID,
		Status:     g.Status,
		CreatedAt:  g.CreatedAt,
		UpdatedAt:  g.UpdatedAt,
		Version:    g.Version,
		State:      g.State,
	}, nil
}

// dbc is a common interface for *sql.DB and *sql.Tx.
type dbc interface {
	QueryContext(ctx context.Context, query string, args ...interface{}) (*sql.Rows, error)
	QueryRowContext(context.Context, string, ...interface{}) *sql.Row
}

// row is a common interface for *sql.Rows and *sql.Row.
type row interface {
	Scan(dest ...interface{}) error
}
